plugins {
    id 'java'
    id 'com.gtnewhorizons.retrofuturagradle' version '2.0.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

repositories {
    mavenCentral()
    maven {
        name 'GTNH Maven'
        url 'https://nexus.gtnewhorizons.com/repository/public/'
    }
    maven {
         name 'cursemaven'
         url "https://www.cursemaven.com"
    }
}



dependencies {
//    implementation "curse.maven:applecore-224472:2969118"
}





version = "1.0.0"
base {
    archivesName = "yourmod"
}

minecraft {
    mcVersion = '1.12.2'
    mcpMappingChannel = 'stable'
    mcpMappingVersion = '39'
    
    
}
